name: "New Spider: GeoMe"
description: A spider using the GeoMe storefinder. Makes requests to `https://*.geoapp.me/api/`
labels: "Store finder: GeoMe"
body:
  - type: input
    attributes:
      label: Brand name
      placeholder: McDonald's
    validations:
      required: true
  - type: input
    attributes:
      label: Wikidata ID
      placeholder: Q38076
      description: >-
        If possible get the ID from
        [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page)
  - type: input
    attributes:
      label: API Key
      description:  Found as `https://{api_key}.geoapp.me/api/`
  - type: input
    attributes:
      label: API Version
      placeholder: v1
      description: Found as `https://xyz.geoapp.me/api/{version}`
  - type: textarea
    attributes:
      label: Other detail
      description: Any other relevant information or sample code
