name: "New Spider: Storemapper"
description: A spider using the Storemapper storefinder. Makes requests to `https://storemapper-herokuapp-com.global.ssl.fastly.net/api/users/`
labels: "Store finder: Storemapper"
body:
  - type: input
    attributes:
      label: Brand name
      placeholder: McDonald's
    validations:
      required: true
  - type: input
    attributes:
      label: Wikidata ID
      placeholder: Q38076
      description: >-
        If possible get the ID from
        [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page)
  - type: input
    attributes:
      label: API Key
      description: Found in urls as `/api/users/{key}`
  - type: textarea
    attributes:
      label: Other detail
      description: Any other relevant information or sample code
