name: "New Spider: Amrest EU"
description: A spider using the Amrest EU storefinder
labels: "Store finder: Amrest EU"
body:
  - type: input
    attributes:
      label: Brand name
      placeholder: McDonald's
    validations:
      required: true
  - type: input
    attributes:
      label: Wikidata ID
      placeholder: Q38076
      description: >-
        If possible get the ID from
        [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page)
  - type: textarea
    attributes:
      label: Other detail
      description: Any other relevant information or sample code
