name: "New Spider: Store Locator Plus (cloud)"
description: A spider using the Store Locator Plus (cloud) storefinder. Makes requets to `https://dashboard.storelocatorplus.com`
labels: "Store finder: Store Locator Plus Cloud"
body:
  - type: input
    attributes:
      label: Brand name
      placeholder: McDonald's
    validations:
      required: true
  - type: input
    attributes:
      label: Wikidata ID
      placeholder: Q38076
      description: >-
        If possible get the ID from
        [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page)
  - type: input
    attributes:
      label: API Key
      description: Found in urls as `api_key={api_key}`

  - type: input
    attributes:
      label: Dataset
      description: Found in urls as `https://dashboard.storelocatorplus.com/{dataset}/`

  - type: textarea
    attributes:
      label: Other detail
      description: Any other relevant information or sample code
