name: "New Spider: Where2GetIt"
description: A spider using the Where2GetIt storefinder. Make requests to `https://hosted.where2getit.com/{api_brand_name}/rest/getlist`
labels: "Store finder: Where2GetIt"
body:
  - type: input
    attributes:
      label: Brand name
      placeholder: McDonald's
    validations:
      required: true
  - type: input
    attributes:
      label: Wikidata ID
      placeholder: Q38076
      description: >-
        If possible get the ID from
        [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page)
  - type: input
    attributes:
      label: API Brand Name
      description: Extract from an AJAX request for `https://hosted.where2getit.com/{api_brand_name}/rest/getlist`
  - type: textarea
    attributes:
      label: Other detail
      description: Any other relevant information or sample code
