name: "New Spider: Woosmap"
description: A spider using the Woosmap storefinder. Makes requests to `https://api.woosmap.com/stores?key={key}`
labels: "Store finder: Woosmap"
body:
  - type: input
    attributes:
      label: Brand name
      placeholder: McDonald's
    validations:
      required: true
  - type: input
    attributes:
      label: Wikidata ID
      placeholder: Q38076
      description: >-
        If possible get the ID from
        [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page)
  - type: input
    attributes:
      label: API Key
      description: Found in urls as `https://api.woosmap.com/stores?key={api_key}`
  - type: textarea
    attributes:
      label: Other detail
      description: Any other relevant information or sample code
