name: "New Spider: Sylinder"
description: A spider using the Sylinder storefinder. Makes requests to `https://api.ngdata.no/sylinder/stores/v1/extended-info?chainId={app_key}`
labels: "Store finder: Sylinder"
body:
  - type: input
    attributes:
      label: Brand name
      placeholder: McDonald's
    validations:
      required: true
  - type: input
    attributes:
      label: Wikidata ID
      placeholder: Q38076
      description: >-
        If possible get the ID from
        [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page)
  - type: input
    attributes:
      label: API Key
      description: Found in urls as `?chainId={app_key}`
  - type: textarea
    attributes:
      label: Other detail
      description: Any other relevant information or sample code
