name: "New Spider: Yext"
description: A spider using the Yext storefinder. Makes requests to `/v2/accounts/me/entities`
labels: "Store finder: Yext"
body:
  - type: input
    attributes:
      label: Brand name
      placeholder: McDonald's
    validations:
      required: true
  - type: input
    attributes:
      label: Wikidata ID
      placeholder: Q38076
      description: >-
        If possible get the ID from
        [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page)
  - type: input
    attributes:
      label: Sample URL
  - type: input
    attributes:
      label: API Key
      description: Found in `entities?api_key={api_key}&v={api_version}`
  - type: input
    attributes:
      label: API Version
      description: Found in `entities?api_key={api_key}&v={api_version}`
  - type: textarea
    attributes:
      label: Other detail
      description: Any other relevant information or sample code
