name: New Spider: Uberall
description: A spider using the Uberall storefinder
labels: "Store finder: Uberall"
body:
  - type: input
    attributes:
      label: Brand name
      placeholder: McDonald's
    validations:
      required: true
  - type: input
    attributes:
      label: Wikidata ID
      placeholder: Q38076
      description: >-
        If possible get the ID from
        [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page)
  - type: input
    attributes:
      label: API key
      description: https://uberall.com/api/storefinders/**key**/locations/all
