name: "New Spider: Metizsoft"
description: A spider using the Metizsoft storefinder. Makes requests to `storelocator.metizapps.com`
labels: "Store finder: Metizsoft"
body:
  - type: input
    attributes:
      label: Brand name
      placeholder: McDonald's
    validations:
      required: true
  - type: input
    attributes:
      label: Wikidata ID
      placeholder: Q38076
      description: >-
        If possible get the ID from
        [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page)
  - type: input
    attributes:
      label: Shopify URL
      placeholder: https://{brand-name}.myshopify.com
  - type: textarea
    attributes:
      label: Other detail
      description: Any other relevant information or sample code
