name: "New Spider: Storepoint"
description: A spider using the Storepoint storefinder. Makes requests to `https://api.storepoint.co/v1/{key}/locations`
labels: "Store finder: Storepoint"
body:
  - type: input
    attributes:
      label: Brand name
      placeholder: McDonald's
    validations:
      required: true
  - type: input
    attributes:
      label: Wikidata ID
      placeholder: Q38076
      description: >-
        If possible get the ID from
        [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page)
  - type: input
    attributes:
      label: API Key
      description: Found in urls as `https://api.storepoint.co/v1/{key}/locations`
  - type: textarea
    attributes:
      label: Other detail
      description: Any other relevant information or sample code
