name: "New Spider: Metalocator"
description: A spider using the Metalocator storefinder. Makes requests to `https://code.metalocator.com/`
labels: "Store finder: Metalocator"
body:
  - type: input
    attributes:
      label: Brand name
      placeholder: McDonald's
    validations:
      required: true
  - type: input
    attributes:
      label: Wikidata ID
      placeholder: Q38076
      description: >-
        If possible get the ID from
        [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page)
  - type: input
    attributes:
      label: Brand ID
      description: Found in `/webapi/api/search/?Itemid={brand_id}`
  - type: input
    attributes:
      label: Country List
      description: Found in `/webapi/api/search/?Itemid={brand_id}&country={country}`
  - type: textarea
    attributes:
      label: Other detail
      description: Any other relevant information or sample code
